global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # FastAPI application metrics
  - job_name: "fastapi-app"
    static_configs:
      - targets: ["app:8000"]
    metrics_path: /metrics
    scrape_interval: 5s

  # Node exporter for system metrics (optional)
  # - job_name: "node"
  #   static_configs:
  #     - targets: ["node-exporter:9100"]

  # PostgreSQL metrics (optional)
  # - job_name: "postgres"
  #   static_configs:
  #     - targets: ["postgres-exporter:9187"]

  # Elasticsearch metrics (optional)
  # - job_name: "elasticsearch"
  #   static_configs:
  #     - targets: ["elasticsearch:9200"]
  #   metrics_path: /_prometheus/metrics 